---
abstract: 'Modules that LESPEA uses on a daily basis'
author:
  - 'Adam Lesperance <lespea@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102221, CPAN::Meta::Converter version 2.102160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-LESPEA
requires:
  DBD::CSV: 0
  DBD::ODBC: 0
  DBI: 0
  DateTime::Format::DateParse: 0
  Devel::NYTProf: 0
  Dist::Zilla: 0
  Dist::Zilla::App::Command::cover: 0
  Dist::Zilla::Plugin::Bugtracker: 0
  Dist::Zilla::Plugin::CheckChangeLog: 0
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::CheckChangesTests: 0
  Dist::Zilla::Plugin::CompileTests: 0
  Dist::Zilla::Plugin::CriticTests: 0
  Dist::Zilla::Plugin::Git: 0
  Dist::Zilla::Plugin::HasVersionTests: 0
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::KwaliteeTests: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::MinimumVersionTests: 0
  Dist::Zilla::Plugin::PodSpellingTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::PortabilityTests: 0
  Dist::Zilla::Plugin::Prepender: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::ReadmeMarkdownFromPod: 0
  Dist::Zilla::Plugin::ReportVersions: 0
  Dist::Zilla::Plugin::Repository: 0
  Dist::Zilla::Plugin::SynopsisTests: 0
  Dist::Zilla::Plugin::UnusedVarsTests: 0
  Exporter::Easy: 0
  File::HomeDir: 0
  File::ShareDir: 0
  File::Slurp: 0
  Getopt::Long::Descriptive: 0
  HTML::Tree: 0
  HTML::TreeBuilder::XPath: 0
  JSON: 0
  JSON::Any: 0
  JSON::XS: 0
  List::MoreUtils: 0
  Math::Big: 0
  Math::Big::Factors: 0
  Module::Build: 0
  Module::Install: 0
  Module::Install::AuthorTests: 0
  Module::Install::ExtraTests: 0
  Module::Starter: 0
  Moose: 0
  MooseX::App::Cmd: 0
  MooseX::Method::Signatures: 0
  MooseX::Types::Common: 0
  MooseX::Types::Structured: 0
  Net::CIDR::Lite: 0
  Net::DNS: 0
  Net::IP: 0
  Net::Netmask: 0
  Net::Ping: 0
  Perl::Critic: 0
  Perl::MinimumVersion: 0
  Perl::PrereqScanner: 0
  Pod::Coverage::TrustPod: 0
  Pod::Elemental::Transformer::List: 0
  Pod::Weaver: 0
  Pod::Weaver::Section::Support: 0
  Readonly::XS: 0
  Regexp::Common: 0
  Spreadsheet::ParseExcel: 0
  Spreadsheet::Read: 0
  Spreadsheet::WriteExcel: 0
  Test::CPAN::Meta: 0
  Test::Most: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Text::CSV_XS: 0
  Try::Tiny: 0
  YAML: 0
  YAML::Any: 0
  YAML::Syck: 0
  YAML::XS: 0
  autodie: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Task-BeLike-LESPEA
  repository: git://github.com/lespea/Task-BeLike-LESPEA
version: 1.10
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: GatherDir
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: 0.02
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: CriticTests
      version: 1.102280
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: HasVersionTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: MetaTests
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: MinimumVersionTests
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: PortabilityTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: ReadmeFromPod
      version: 0.12
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: KwaliteeTests
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: AutoPrereq
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: ShareDir
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: Bugtracker
      version: 1.101490
    -
      class: Dist::Zilla::Plugin::Repository
      name: Repository
      version: 0.13
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: ModuleBuild
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101640
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: CheckChangeLog
      version: 0.01
    -
      class: Dist::Zilla::Plugin::CheckChangesTests
      name: CheckChangesTests
      version: 1.100900
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: CheckChangesHasContent
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: Git::Check
      version: 1.102090
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: UploadToCPAN
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: Git::Tag
      version: 1.102090
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: Commit_Changes
      version: 1.102090
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: Git::Push
      version: 1.102090
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102221
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102221
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102221
