---
abstract: 'Modules that LESPEA uses on a daily basis'
author:
  - 'Adam Lesperance <lespea@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-LESPEA
no_index:
  directory:
    - inc
    - t
    - xt
    - utils
    - share
    - example
    - examples
  file:
    - README.html
requires:
  DBD::CSV: 0.000000
  DBD::ODBC: 0.000000
  DBI: 0.000000
  DateTime::Format::DateParse: 0.000000
  Devel::NYTProf: 0.000000
  Dist::Zilla: 0.000000
  Dist::Zilla::PluginBundle::Author::LESPEA: 1.003000
  Exporter::Easy: 0.000000
  File::HomeDir: 0.000000
  File::ShareDir: 0.000000
  File::Slurp: 0.000000
  Getopt::Long::Descriptive: 0.000000
  HTML::Tree: 0.000000
  HTML::TreeBuilder::XPath: 0.000000
  JSON: 0.000000
  JSON::Any: 0.000000
  JSON::XS: 0.000000
  List::MoreUtils: 0.000000
  Math::Big: 0.000000
  Math::Big::Factors: 0.000000
  Module::Build: 0.000000
  Module::Install: 0.000000
  Module::Install::AuthorTests: 0.000000
  Module::Install::ExtraTests: 0.000000
  Module::Starter: 0.000000
  Moose: 0.000000
  MooseX::App::Cmd: 0.000000
  MooseX::Method::Signatures: 0.000000
  MooseX::Types::Common: 0.000000
  MooseX::Types::DateTimeX: 0.000000
  MooseX::Types::Structured: 0.000000
  Net::CIDR::Lite: 0.000000
  Net::DNS: 0.000000
  Net::IP: 0.000000
  Net::Netmask: 0.000000
  Net::Ping: 0.000000
  Perl::Critic: 0.000000
  Readonly::XS: 0.000000
  Regexp::Common: 0.000000
  Spreadsheet::ParseExcel: 0.000000
  Spreadsheet::Read: 0.000000
  Spreadsheet::WriteExcel: 0.000000
  Test::Most: 0.000000
  Test::Perl::Critic: 0.000000
  Test::Pod: 0.000000
  Test::Pod::Coverage: 0.000000
  Text::CSV_XS: 0.000000
  Try::Tiny: 0.000000
  YAML: 0.000000
  YAML::Any: 0.000000
  YAML::Syck: 0.000000
  YAML::XS: 0.000000
  autodie: 0.000000
  namespace::autoclean: 0.000000
  perl: 5.008
  utf8: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Task-BeLike-LESPEA
  homepage: http://search.cpan.org/dist/Task-BeLike-LESPEA
  repository: git://github.com/lespea/task-belike-lespea.git
version: 2.001000
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::LESPEA/@Filter/GatherDir'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::LESPEA/@Filter/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::LESPEA/@Filter/UploadToCPAN'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@Author::LESPEA/@Filter/ArchiveRelease'
      version: 3.01
    -
      class: Dist::Zilla::Plugin::AutoMetaResources
      name: '@Author::LESPEA/@Filter/AutoMetaResources'
      version: 1.110050
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::LESPEA/@Filter/Authority'
      version: 1.005
    -
      class: Dist::Zilla::Plugin::SynopsisTests
      name: '@Author::LESPEA/@Filter/SynopsisTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::LESPEA/@Filter/PkgVersion'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::LESPEA/@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::LESPEA/@Filter/NextRelease'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::LESPEA/@Filter/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::LESPEA/@Filter/AutoPrereqs'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::LESPEA/@Filter/MetaConfig'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@Author::LESPEA/@Filter/CompileTests'
      version: 1.110930
    -
      class: Dist::Zilla::Plugin::ConsistentVersionTest
      name: '@Author::LESPEA/@Filter/ConsistentVersionTest'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@Author::LESPEA/@Filter/CriticTests'
      version: 1.111450
    -
      class: Dist::Zilla::Plugin::DistManifestTests
      name: '@Author::LESPEA/@Filter/DistManifestTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::LESPEA/@Filter/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Author::LESPEA/@Filter/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@Author::LESPEA/@Filter/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::LESPEA/@Filter/MetaTests'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@Author::LESPEA/@Filter/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@Author::LESPEA/@Filter/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::LESPEA/@Filter/PodCoverageTests'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::LESPEA/@Filter/PodSyntaxTests'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@Author::LESPEA/@Filter/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@Author::LESPEA/@Filter/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::LESPEA/@Filter/Test::CPAN::Changes'
      version: 0.005
    -
      class: Dist::Zilla::Plugin::SpellingCommonMistakesTests
      name: '@Author::LESPEA/@Filter/SpellingCommonMistakesTests'
      version: 1.001000
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::LESPEA/@Filter/ExtraTests'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::LESPEA/@Filter/PruneCruft'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::LESPEA/@Filter/ManifestSkip'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::LESPEA/@Filter/ExecDir'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::LESPEA/@Filter/ShareDir'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::LESPEA/@Filter/ModuleBuild'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::LESPEA/@Filter/MakeMaker'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::DualBuilders
      name: '@Author::LESPEA/@Filter/DualBuilders'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::LESPEA/@Filter/MetaNoIndex'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::LESPEA/@Filter/License'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::LESPEA/@Filter/InstallGuide'
      version: 1.101461
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::LESPEA/@Filter/MetaJSON'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::LESPEA/@Filter/MetaYAML'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::LESPEA/@Filter/html.build'
      version: 0.103522
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::LESPEA/@Filter/text.build'
      version: 0.103522
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::LESPEA/@Filter/pod.root'
      version: 0.103522
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::LESPEA/@Filter/Manifest'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::LESPEA/@Filter/TestRelease'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::LESPEA/@Filter/ConfirmRelease'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: ReportVersions::Tiny
      version: 1.03
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::Signature
      name: Signature
      version: 1.100930
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: Git::Check
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: Commit_Changes
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: Git::Tag
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: Git::Push
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200007
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.200007
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200007
x_authority: cpan:LESPEA
